version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./user_config.json:/app/user_config.json
